[FileDialog]
history=file:///home/djamieson/Dropbox/Documents/_UNI/YEAR2/TRI1/COMPX234/Books, file:///home/djamieson, file:///home/djamieson/Documents/Linux, file:///home/djamieson/Dropbox/Documents/_UNI/Linux Device Drivers, file:///home/djamieson/Downloads
lastVisited=file:///home/djamieson
qtVersion=6.11.1
shortcuts=file:, file:///home/djamieson
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd7\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf4\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0i\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
