ipc = true
splash = false

wallpaper {
    monitor = 
    #path = /home/djamieson/Documents/Wallpaper/supernova.jpg
    path = /home/djamieson/Documents/Wallpaper/pink-anime-back.jpg
    fit_mode = cover
}
